// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw0kKtkN8vqYIJBIXPM5wzy6VB6pqGMgU',
    appId: '1:559376582323:web:96038668c6e0a8ba0892c6',
    messagingSenderId: '559376582323',
    projectId: 'maternal-child-health-tracker',
    authDomain: 'maternal-child-health-tracker.firebaseapp.com',
    storageBucket: 'maternal-child-health-tracker.firebasestorage.app',
    measurementId: 'G-96XRGNVJQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCCSiDhUZexQ16diFkdmR1oNDGArnCdi8',
    appId: '1:559376582323:android:e0f51f4f1b71e4fc0892c6',
    messagingSenderId: '559376582323',
    projectId: 'maternal-child-health-tracker',
    storageBucket: 'maternal-child-health-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQokvxr8ECh8H0M76GoN9IaHkCXvFEsuQ',
    appId: '1:559376582323:ios:ccbd696170b33d760892c6',
    messagingSenderId: '559376582323',
    projectId: 'maternal-child-health-tracker',
    storageBucket: 'maternal-child-health-tracker.firebasestorage.app',
    iosClientId: '559376582323-hera7hminjpitomvtqbqvlvql2f8e6rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.maternalHealthApp',
  );
}
